#!/bin/sh

CC=cc

CFLAGS_LANGUAGE="-std=c99 -pthread"
CFLAGS_OPTIMIZE="-Os"
CFLAGS_DEBUG="-g"
CFLAGS_WARNINGS="-Wall -Wextra -Wno-unused"
CFLAGS_SOURCE="-D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L"
CFLAGS_INCLUDE="-Iinclude -I/usr/local/include"

CFLAGS_BASE="${CFLAGS_LANGUAGE} ${CFLAGS_OPTIMIZE} ${CFLAGS_DEBUG} ${CFLAGS_WARNINGS} ${CFLAGS_SOURCE} ${CFLAGS_INCLUDE}"

LDFLAGS="-L/usr/local/lib -ldl -ltcc"

LIBTCC_I="-I/usr/local/include"

CFLAGS="${CFLAGS_BASE} ${LIBTCC_I}"

run() {
    echo "Run: $*"
    "$@"
}

run ${CC} ${CFLAGS} ${LDFLAGS} -o bin/cplr source/cplr*.c source/cext*.c source/cpkg.c

