#!/bin/bash

# errors on
set -e

# program name and test directory
P="$0"
N="$(basename $0)"
D="$(dirname $0)"
T="${D}/tests"

# load library
LIB_SH=true
. "${D}/lib.sh"

main() {
    local test="$1"
    local file="$2"
    if [ -z "${file}" ]; then
        file="cmd"
    fi
    if [ -z "${test}" ]; then
        echo "Usage: ${N} <test> [<file>]"
        echo ""
        echo "Edits a test file."
        echo ""
        echo "Files:"
        echo "  *cmd"
        echo "   inp(ut)"
        echo "   out(put)"
        echo "   res(ult)"
        echo ""
        exit 1
    fi

    local path="${T}/${test}.base.${file}"
    run_editor "${path}" && if [ -f "${path}" ]; then
        "${D}/testgen" "${test}"
    fi
}

main "$@"
